// @codekit-prepend "../bower_components/jquery/dist/jquery.min.js"

// @codekit-prepend "../bower_components/formstone/dist/js/core.js"
// @codekit-prepend "../bower_components/formstone/dist/js/touch.js"
// @codekit-prepend "../bower_components/formstone/dist/js/transition.js"
// @codekit-prepend "../bower_components/formstone/dist/js/dropdown.js"
// @codekit-prepend "../bower_components/formstone/dist/js/mediaquery.js"
// @codekit-prepend "../bower_components/formstone/dist/js/swap.js"
// @codekit-prepend "../bower_components/formstone/dist/js/navigation.js"
// @codekit-prepend "../bower_components/formstone/dist/js/cookie.js"
// @codekit-prepend "../bower_components/formstone/dist/js/tabs.js"
// @codekit-prepend "../bower_components/formstone/dist/js/equalize.js"

// @codekit-prepend "../bower_components/components-modernizr/modernizr.js"
// @codekit-prepend "../bower_components/jquery.transit/jquery.transit.js"